version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
      
      # - ./mysql:/root/mysql
      # - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: card_game 
      MYSQL_USER: cardGame
      MYSQL_PASSWORD: 'card'
      MYSQL_ROOT_PASSWORD: 'password'

  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
      - ./mysql:/var/www/mysql
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  db_data: {}